### PR TITLE
ability to search with parameters

### PR DESCRIPTION
**Pull request by SKaistrenko**
Need to be able to search using `fromData` and `pageSize`. Thought it might be useful for others.
https://developer.apple.com/documentation/apple_news/search_articles_in_a_section

### CODE REVIEW

**Comment by Robert-Fairley** [comment]
Looks like I've fallen behind the API. Thanks for the pull.

**Comment by SKaistrenko** [comment]
Any chance you know when to expect it this change to make it to NPM?

**Comment by robertfairley** [comment]
@SKaistrenko 
Looks like I've fallen behind the API.

I just published `0.13.1` to NPM. I'll have to sort out those version numbers after I get the chance to make some improvements and get some proper tests implemented.

 Thanks for the pull!

**Comment by SKaistrenko** [comment]
Awesome, thank you so much!

**Comment by SKaistrenko** [comment]
Also, Readme doesn't describe search functionality - I forgot to add that

**Comment by SKaistrenko** [comment]
@robertfairley Also one last question - I added the Promise wrappers on top of each method in a separate file so that you can use them with async/await on .then().catch() - would you like me to push those too?

**Comment by Robert-Fairley** [comment]
@SKaistrenko Feel free to open a PR! It's a good idea in general. My only hangup is backwards compatibility. If that compatibility persists, then we might as well have Promises available as well!

**Comment by SKaistrenko** [comment]
Sure thing, that's why they are separate from main methods. I'll clean up and try to push over the weekend

**Comment by Robert-Fairley** [comment]
Sounds good!

**Comment by SKaistrenko** [comment]
Your package saved me from complete insanity. Cause first I almost did it myself, but after spending a couple of days debugging different POST request issues I was losing it...

**Comment by Robert-Fairley** [comment]
You're not alone. I was running into a large number of issues even though the requests seemed formed to Apple's spec. I came across this repository: https://github.com/micnews/apple-news

They did the real lifting. I needed TypeScript definitions and wanted to modernize some of the formatting, and theirs seemed to have been abandoned so I decided to create a fresh repo/package, but I have to give credit where credit is due.

**Comment by SKaistrenko** [comment]
Yeah, their package is what I found initially, but had the same concerns about it as you did

**Pull request merged**
